export const neighboringCountries = ['África do Sul', 'Maláui', 'Tanzânia', 'Zâmbia', 'Zimbábue', 'Essuatíni']

export const neighboringProvinces = {
	'Cabo Delgado': ['Niassa', 'Nampula'],
	Niassa: ['Cabo Delgado', 'Nampula', 'Tete', 'Zambézia'],
	Nampula: ['Cabo Delgado', 'Niassa', 'Zambézia'],
	Zambézia: ['Niassa', 'Nampula', 'Tete', 'Sofala'],
	Tete: ['Niassa', 'Manica', 'Sofala', 'Zambézia'],
	Manica: ['Tete', 'Inhambane', 'Sofala', 'Gaza'],
	Sofala: ['Inhambane', 'Manica', 'Zambézia', 'Tete'],
	Gaza: ['Inhambane', 'Maputo', 'Manica'],
	Inhambane: ['Sofala', 'Gaza', 'Manica'],
	Maputo: ['Gaza', 'Maputo (Cidade)'],
	'Maputo (Cidade)': ['Maputo'],
}

export const neighboringDistricts = {
	// Niassa
	Chimbunila: [
		'Cuamba',
		'Lago',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Sanga',
	],
	Cuamba: ['Chimbunila',
		'Lago',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Sanga',],
	Lago: [
      'Chimbunila',
		'Cuamba',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Sanga',  
    ],
	Lichinga: [
        'Chimbunila',
		'Lago',
		'Cuamba',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Sanga',
    ],
	Majune: [
        'Chimbunila',
		'Lago',
		'Lichinga',
		'Cuamba',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Sanga',
    ],
	Mandimba: [
        'Chimbunila',
		'Lago',
		'Lichinga',
		'Majune',
		'Cuamba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Sanga',
    ],
	Marrupa: [
        'Chimbunila',
		'Lago',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Cuamba',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Sanga',
    ],
	Maúa: [
        'Chimbunila',
		'Lago',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Cuamba',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Sanga',
    ],
	Mavago: [
        'Chimbunila',
		'Lago',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Cuamba',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Sanga',
    ],
	Mecanhelas: [
        'Chimbunila',
		'Lago',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Cuamba',
		'Mecula',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Sanga',
    ],
	Mecula: [
        'Chimbunila',
		'Lago',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Cuamba',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Sanga',
    ],
	Metarica: [
        'Chimbunila',
		'Lago',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Cuamba',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Sanga',
    ],
	Muembe: [
        'Chimbunila',
		'Lago',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Cuamba',
		"N'gauma",
		'Nipepe',
		'Sanga',
    ],
	"N'gauma": [
        'Chimbunila',
		'Lago',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Muembe',
		'Cuamba',
		'Nipepe',
		'Sanga',
    ],
	Nipepe: [
        'Chimbunila',
		'Lago',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Cuamba',
		'Sanga',
    ],
	Sanga: [
        'Chimbunila',
		'Lago',
		'Lichinga',
		'Majune',
		'Mandimba',
		'Marrupa',
		'Maúa',
		'Mavago',
		'Mecanhelas',
		'Mecula',
		'Metarica',
		'Muembe',
		"N'gauma",
		'Nipepe',
		'Cuamba',
    ],

	// Cabo Delgado
	Ancuabe: [
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Balama: [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Chiúre: [
		'Ancuabe',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Ibo: [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Macomia: [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Quissanga',
		'Macomia',
	],
	Mecúfi: [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Meluco: [
		'Ancuabe',
		'Chiúre',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Metuge: [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	'Mocímboa da Praia': [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Montepuez: [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Mueda: [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Muidumbe: [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Namuno: [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Nangade: [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Palma: [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	'Pemba (Cidade)': [
		'Ancuabe',
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Quissanga',
		'Macomia',
	],
	Quissanga: [
		'Chiúre',
		'Meluco',
		'Mecúfi',
		'Mocímboa da Praia',
		'Montepuez',
		'Mueda',
		'Palma',
		'Pemba (Cidade)',
		'Metuge',
		'Muidumbe',
		'Namuno',
		'Nangade',
		'Balama',
		'Ibo',
		'Macomia',
		'Macomia',
	],

	// Nampula
	Angoche: ['', 'Aube', 'Boila', 'Namaponda'],
	Eráti: ['Alua', 'Namapa', 'Namiroa'],
	'Ilha de Moçambique': ['Ilha de Moçambique (Sede)', 'Lumbo'],
	Lalaua: ['Lalaua (Sede)', 'Meti'],
	Larde: ['Larde (Sede)', 'Mucuali'],
	Liúpo: ['Liúpo (Sede)', 'Quinga'],
	Malema: ['Malema (Sede)', 'Mutuali', 'Chihulo'],
	Meconta: ['7 de Abril', 'Corrane', 'Meconta (Sede)', 'Namialo'],
	Mecubúri: ['Mecubúri (Sede)', 'Milhana', 'Muite', 'Namina'],
	Memba: ['Chipene', 'Lurio (de Memba)', 'Mazua', 'Memba (Sede)'],
	Mogincual: ['Namige (Sede)', 'Quixaxe'],
	Mogovolas: ['Calipo', 'Iuluti', 'Muatua', 'Nametil', 'Nanhupo-Rio'],
	Moma: ['Chalaua', 'Macone', 'Moma (Sede)'],
	Monapo: ['Itoculo', 'Monapo (Sede)', 'Netia'],
	Mossuril: ['Lunga', 'Matibane', 'Mossuril (Sede)'],
	Muecate: ['Imala', 'Muculuone', 'Muecate (Sede)'],
	Murrupula: ['Chinga', 'Murrupula (Sede)', 'Nihessiue'],
	Nacala: [
		'Muanona',
		'Mutiva (Sede)',
		// "Maiaia",
	],
	'Nacala-a-Velha': ['Covo', 'Nacala-a-Velha (Sede)'],
	Nacarôa: ['Inteta', 'Nacarôa (Sede)', 'Saua-Saua'],
	Nampula: ['Anchilo', 'Nampula (Cidade)'],

	// "Nampula (Cidade)": [
	//   "Central (Sede)",
	//   "Muatala",
	//   "Namicopo",
	//   "Napipine",
	//   "Natikire",
	//   "Muhala",
	// ],
	Rapale: ['Mutivasse', 'Namaita', 'Rapale (Sede)'],
	Ribaué: ['Cunle', 'Iapala', 'Ribaué (Sede)'],

	// Zambezia
	'Alto Molócuè': ['Molócuè (Sede)', 'Nauela'],
	Chinde: ['Chinde (Sede)', 'Micaune'],
	Derre: ['Derre (Sede)', 'Machindo', 'Guerissa'],
	Gilé: ['Alto Ligonha', 'Gilé (Sede)'],
	Gurué: ['Gurué (Sede)', 'Lioma', 'Mepuagiua'],
	Ile: ['Ile (Sede)', 'Namigonha', 'Socone'],
	Inhassunge: ['Gonhane', 'Mucupia'],
	Luabo: ['Chimbazo', 'Luabo (Sede)'],
	Lugela: ['Lugela (Sede)', 'Muabanama', 'Munhamade', 'Tacuane'],
	'Maganja da Costa': ['Baixo Licungo', 'Maganja (Sede)'],
	Milange: ['Majaua', 'Milange (Sede)', 'Mongue'],
	Mocuba: ['Mocuba (Sede)', 'Mugeba', 'Namanjavira'],
	Mocubela: ['Bajone', 'Mocubela (Sede)'],
	Molumbo: ['Corromana', 'Molumbo (Sede)'],
	Mopeia: ['Campo', 'Mopeia (Sede)'],
	Morrumbala: ['Chire', 'Megaza', 'Morrumbala (Sede)'],
	Mulevala: ['Chiraco', 'Mulevala (Sede)'],
	Namacurra: ['Macuse', 'Namacurra (Sede)'],
	Namarroi: ['Namarroi (Sede)', 'Regone'],
	Nicoadala: ['Nicoadala (Sede)'],
	Pebane: ['Mulela', 'Naburi', 'Pebane (Sede)'],
	'Quelimane (Cidade)': [
		'Posto Admin. 1-Sede',
		'Posto Admin. 2',
		'Posto Admin. 3',
		'Posto Admin. 4',
		'Posto Admin. 5',
		'Maquival',
	],

	// Maputo-Cidade
	KaMpfumu: [
		'Alto Maé A',
		'Alto Maé B',
		'Bairro Central A',
		'Bairro Central B',
		'Bairro Central C',
		'Coop',
		'Malhangalene A',
		'Malhangalene B',
		'Polana Cimento A',
		'Polana Cimento B',
		'Sommerschield',
	],

	Nlhamankulu: [
		'Aeroporto A',
		'Aeroporto B',
		'Chamanculo A',
		'Chamanculo B',
		'Chamanculo C',
		'Chamanculo D',
		'Malanga',
		'Minkadjuine',
		'Munhuana',
		'Unidade 7',
		'Xipamanine',
	],

	KaMaxakeni: [
		'Mafalala',
		'Maxaquene A',
		'Maxaquene B',
		'Maxaquene C',
		'Maxaquene D',
		'Polana Caniço A',
		'Polana Caniço B',
		'Urbanização',
	],

	KaMavota: [
		'3 de Fevereiro',
		'Albazine',
		'Costa do Sol',
		'F.P.L.M.',
		'Ferroviário',
		'Hulene A',
		'Hulene B',
		'Laulane',
		'Mahotas',
		'Mavalane A',
		'Mavalane B',
	],

	KaMubukwana: [
		'25 de Junho A',
		'25 de Junho B',
		'Bagamoyo',
		'Inhagóia A',
		'Inhagóia B',
		'Jardim',
		'George Dimitrov',
		'Luis Cabral',
		'Magoanine A',
		'Magoanine B',
		'Magoanine C',
		'Malhazine',
		'Nsalene',
		'Zimpeto',
	],

	KaTembe: ['Chali', 'Chamissava', 'Guachene', 'Incassane', 'Inguide'],

	KaNyaka: ['Inguane', 'Nhaquene', 'Ridzene'],

	// Maputo
	Boane: ['Boane (Sede)', 'Matola-Rio'],
	Magude: ['Magude (Sede)', 'Mahele', 'Mapulanguene', 'Motaze', 'Panjane'],
	Manhiça: ['3 de Fevereiro', 'Calanga', 'Ilha Josina Machel', 'Maluana', 'Manhiça (Sede)', 'Xinavane'],
	Marracuene: ['Machubo', 'Marracuene (Sede)'],
	Matola: ['Infulene', 'Machava', 'Matola (Sede)'],
	Matutuíne: [
		'Bela-Vista (Sede)',
		'Catembe Nsime',
		'Catuane',
		'Machangulo',
		'Zitundo',
		// "Missevene",
	],
	Moamba: ['Moamba (Sede)', 'Pessene', 'Ressano Garcia', 'Sabie'],
	Namaacha: ['Changalane', 'Namaacha (Sede)'],

	// Gaza
	Bilene: ['Incaia', 'Macia (Sede)', 'Macuane', 'Mazivala', 'Messano', 'Praia do Bilene'],
	Chibuto: ['Alto Changane', 'Chaimite', 'Changanine', 'Chibuto (Sede)', 'Godide', 'Malehice'],
	Chicualacuala: [
		'Eduardo Mondlane (Sede)',
		'Pafuri',
		// "Mapai",
	],
	Chigubo: ['Chigubo', 'Dindiza (Sede)'],
	Chókwè: ['Chókwè (Sede)', 'Lionde', 'Macarretane', 'Xilembene'],
	Chongoene: ['Chongoene (Sede)', 'Mazucane', 'Nguzene'],
	Guijá: ['Caniçado (Sede)', 'Chivongoene', 'Mubangoene', 'Nalazi'],
	Limpopo: ['Chicumbane (Sede)', 'Chissano', 'Zongoene'],
	Mabalane: ['Combomune', 'Mabalane (Sede)', 'Ntlavane'],
	Mandlakazi: ['Chibonzane', 'Chidenguele', 'Macuacua', 'Mandlakazi (Sede)', 'Xalala'],
	Mapai: ['Machaila', 'Mapai (Sede)'],
	Massangena: ['Massangena (Sede)', 'Mavue'],
	Massingir: ['Massingir (Sede)', 'Mavodze', 'Zulo'],
	'Xai-Xai (Cidade)': ['Inhamissa', 'Patrice Lumumba', 'Praia de Xai-Xai', 'Xai-Xai (Sede)'],

	// Inhambane
	Funhalouro: ['Funhalouro (Sede)', 'Tome'],
	Govuro: ['Mambone (Sede)', 'Save'],
	Homoíne: ['Homoíne (Sede)', 'Pembe'],
	'Inhambane (Cidade)': [
		'Balane 1',
		'Balane 2',
		'Balane 3',
		'Chamane',
		'Chambale 1',
		'Chambale 2',
		'Conguiana',
		'Guitamatuno',
		'Ilha Inhambane',
		'Josina Machel',
		'Liberdade 1',
		'Liberdade 2',
		'Liberdade 3',
		'Machavenga',
		'Malembuane',
		'Marrambone',
		'Mucucune',
		'Muele 1',
		'Muele 2',
		'Muele 3',
		'Inhamua',
		'Salele',
		'Siquiriva',
	],
	Inharrime: ['Inharrime (Sede)', 'Mucumbi'],
	Inhassoro: ['Bazaruto', 'Inhassoro (Sede)'],
	Jangamo: ['Cumbana', 'Jangamo (Sede)'],
	Mabote: ['Mabote (Sede)', 'Zimane', 'Zinave'],
	Massinga: ['Chicomo', 'Massinga (Sede)'],
	Maxixe: [
		'Bembe',
		'Chambone A (Sede)',
		'Chambone B',
		'Dambo',
		'Eduardo Mondlane',
		'Mabil',
		'Macuamene',
		'Macupula',
		'Malalane',
		'Manhala',
		'Mawewe',
		'Nhabanda',
		'Nhaguiviga',
		'Nhambui',
		'Nhanguila',
		'Rumbana',
		'Tinga-Tinga',
	],
	Morrumbene: ['Mocodoene', 'Morrumbene (Sede)'],
	Panda: ['Mawayela', 'Panda (Sede)', 'Urrene'],
	Vilankulo: ['Mapinhane', 'Vilankulo (Sede)'],
	Zavala: ['Quissico (Sede)', 'Zandamela'],

	// Manica
	Bárue: ['Catandica (Sede)', 'Choa', 'Nhampassa'],
	'Chimoio (Cidade)': ['Posto Admin. 1 (Sede)', 'Posto Admin. 2', 'Posto Admin. 3', 'Posto Admin. 4'],
	Gondola: ['Amatongas', 'Cafumpe', 'Gondola (Sede)', 'Inchope'],
	Guro: ['Guro (Sede)', 'Mandie', 'Mungari', 'Nhamassonge'],
	Macate: ['Macate (Sede)', 'Zembe'],
	Machaze: ['Chibote (Sede)', 'Save'],
	Macossa: ['Macossa (Sede)', 'Nguawala', 'Nhamagua'],
	Manica: ['Manica (Sede)', 'Machipanda', 'Mavonde', 'Messica'],
	Mossurize: ['Chiurairue', 'Dacata', 'Espungabera (Sede)'],
	Sussundenga: ['Dombe', 'Muoha', 'Rotanda', 'Sussundenga (Sede)'],
	Tambara: ['Buzua', 'Nhacafula', 'Nhacolo (Sede)'],
	Vanduzi: ['Matsinho', 'Vanduzi (Sede)'],

	// Sofala
	'Beira (Cidade)': ['Chiveve (Sede)', 'Manga Loforte', 'Munhava', 'Nhamizua', 'Nhangau'],
	Búzi: ['Búzi (Sede)', 'Estaquinha', 'Sofala'],
	Caia: ['Caia (Sede)', 'Murraça', 'Sena'],
	Chemba: ['Chemba (Sede)', 'Chiramba', 'Mulima'],
	Cheringoma: ['Inhaminga (Sede)', 'Inhamitanga'],
	Chibabava: ['Chibabava (Sede)', 'Goonda', 'Muxungue'],
	Dondo: ['Dondo (Sede)', 'Mafambisse'],
	Gorongosa: ['Gorongosa (Sede)', 'Nhamadze', 'Vanduzi'],
	Machanga: ['Divinhe', 'Machanga (Sede)'],
	Maringué: ['Canxixe', 'Maringué (Sede)', 'Subwe'],
	Marromeu: ['Chupanga', 'Marromeu (Sede)'],
	Muanza: ['Galinha', 'Muanza (Sede)'],
	Nhamatanda: ['Nhamatanda (Sede)', 'Tica'],

	// Tete
	Angónia: ['Domue', 'Ulongoe (Sede)'],
	'Cahora-Bassa': ['Chintholo', 'Chitima (Sede)', 'Songo'],
	Changara: ['Chioco', 'Luenha (Sede)'],
	Chifunde: ['Chifunde (Sede)', 'Mualadzi', "N'Sadzu"],
	Chiuta: ['Kazula', 'Manje (Sede)'],
	Dôa: ['Chueza', 'Dôa (Sede)'],
	Macanga: ['Chidzolomondo', 'Furancungo (Sede)'],
	Magoé: ['Chinthopo', 'Mphende (Sede)', 'Mukumbura'],
	Marara: ['Marara (Sede)', 'Mufa-Boroma'],
	Marávia: ['Chipera', 'Chiputu', 'Fingoe (Sede)', 'Malowera'],
	Moatize: ['Kambulatsitsi', 'Moatize (Sede)', 'Zobue'],
	Mutarara: ['Chare', 'Inhangoma', 'Nhamayabué (Sede)'],
	'Tete (Cidade)': [
		'Chingodzi',
		'Degue',
		'Filipe Samuel Magaia',
		'Francisco Manyanga',
		'Josina Machel',
		'Mateus Sansão Muthemba',
		'Matundo',
		'Mpádué',
		'Samora Machel',
	],
	Tsangano: ['Ntengo-Wa-Mbalame', 'Tsangano (Sede)'],
	Zumbo: ['Muze', 'Zambue', 'Zumbo (Sede)'],
}
