/* eslint-disable prettier/prettier */

type VillageProps = {
    [key: string]: string[];
  }
  
  const villages: VillageProps = {
    // Cabo Delgado
    "Ancuabe (Sede)": ["Ancuabe (Sede)", "Gihote", "Nacuale"],
    Metoro: ["Metoro (Sede)", "Salaue"],
    Mesa: ["Teule", "Campine", "Minheuene", "Nanjua"],
    "Balama (Sede)": ["Ntete", "Muripa"],
    Kuekue: ["Tauame", "Jamira"],
    Impiri: ["Sivaca", "Namara"],
    Mavala: ["Mpaca"],
    "Chiúre (Sede)": ["Chiúre (Sede)", "Milamba", "Jonga"],
    Katapua: ["Katapua (Sede)", "Meculane"],
    Ocua: ["Ocua (Sede)", "Marera", "Samora Machel"],
    "Chiúre Velho": ["Mocolene", "Mugipala"],
    Mazeze: ["Mazeze (Sede)", "Morrocue", "Javaro"],
    Namogelia: ["Namogelia (Sede)", "Bilibiza"],
    Ibo: ["Ibo (Sede)", "Matemo"],
    Quirimba: ["Quirimba (Sede)"],
    "Macomia (Sede)": ["Macomia (Sede)", "Nacate", "Nguida"],
    Mucojo: ["Mucojo (Sede)", "Pangane", "Naunde", "Manica"],
    Quiterajo: ["Quiterajo (Sede)", "Ilala"],
    Chai: ["Chai (Sede)", "Nkoe"],
    "Mecufi (Sede)": ["Muaria", "Sembene", "Natuco"],
    Murrebue: ["Maueia", "Muitua"],
    "Meluco (Sede)": ["Meluco (Sede)", "Mitepo", "Miinhamba", "Ravia"],
    Muaguide: ["Muaguide (Sede)", "Citate", "Iba", "Mitambo"],
    "Metuge (Sede)": ["Metuge (Sede)", "Nacuta", "Messanja"],
    Mieze: ["Mieze (Sede)", "Nanila"],
    "Mocimboa da Praia (Sede)": ["Mocimboa da Praia (Sede)", "Quelimane"],
    Diaca: ["Diaca (Sede)", "Nnango"],
    Mbau: ["Mbau (Sede)", "Marere"],
    "Montepuez (Sede)": ["Montepuez (Sede)", "Mirage", "Nacate"],
    Mapupulo: ["Mapupulo (Sede)", "Massingir", "Mputo"],
    Namanhumir: ["Namanhumir (Sede)", "Mpupene"],
    Mirate: ["Mirate (Sede)", "Mararange", "Unidade", "Chipembe"],
    Nairoto: ["Nairoto (Sede)", "Nacololo"],
    "Mueda (Sede)": ["Mueda (Sede)", "Mpeme", "Miula"],
    Imbuo: ["Imbuo (Sede)", "Namaua"],
    "N'gapa": ["N'gapa (Sede)", "Nachitenge", "Nonge", "Chipingo"],
    Chapa: ["Chapa (Sede)", "Nanhala", "Lipelua"],
    Negomano: ["Negomano (Sede)", "Navara"],
    Chitunda: ["Chitunda", "Mienguelewa"],
    Miteda: ["Miteda", "Muatide"],
    Muidumbe: ["Mapate", "Muidumbe", "Namacande", "Nampanha"],
    "Namuno (Sede)": [
      "Namuno (Sede)",
      "Milipone",
      "Mahussiine",
      "Nicuita",
      "Nicane",
    ],
    Ncumpe: ["Ncumpe (Sede)", "Nassupia", "Pambara"],
    Machoca: ["Machoca (Sede)", "Phomé", "Muchermele"],
    Meloco: ["Meloco (Sede)", "Muatuca"],
    Hucula: ["Hucula (Sede)", "Mavo"],
    Papai: ["Papai (Sede)", "Luli"],
    "Nangade (Sede)": ["Nangade (Sede)", "Litingina"],
    Ntamba: ["Itanda", "Mualela", "Nambedo"],
    "Palma (Sede)": ["Palma (Sede)"],
    Quitunda: ["Quitunda (Sede)", "Mute"],
    Pundanhar: ["Pundanhar (Sede)", "Nhica de Rovuma"],
    Quionga: ["Quionga (Sede)", "Quirinde"],
    Olumbi: ["Olumbi (Sede)", "Quissengue"],
    Cariáco: ['Cariáco'],
    "Eduardo Mondlane": ["Eduardo Mondlane"],
    Ingonane: ["Ingonane"],
    "Mahate (Pemba)": ["Mahate"],
    Bilibiza: ["Bilibiza (Sede)", "Tororo", "Ntapuate"],
    "Quissanga (Sede)": ["Quissanga (Sede)"],
    Mahate: ["Mahate (Sede)", "Cagembe", "Namaluco"],
  
    // Niassa
    "Chimbunila (Sede)": ["Chimbunila (Sede)"],
    Lione: ["Lione-Sede", "Chala"],
    Mussa: ["Mussa (Sede)", "Cholue", "Namuanica"],
    "Cuamba (Sede)": ["Cuamba-Sede"],
    Etatara: ["Etatara (Sede)", "Malapa", "Titimane"],
    "Lurio (de Cuamba)": ["Lurio (Sede)", "Mutetere"],
    Mepica: ["Mepica (Sede)", "Mepolage", "Napacala", "Mitucue"],
    Cobue: ["Cobue (Sede)", "Ngôo", "Ngofi", "Lupilichi", "Wikihi"],
    Lunho: ["Lunho (Sede)", "Messumba", "Mepochi"],
    Maniamba: ["Maniamba (Sede)", "Bandez"],
    Meluluca: ["Meluluca (Sede)", "Timba"],
    "Lichinga (Sede)": ["Lichinga (Cidade)"],
    Meponda: ["Meponda (Sede)"],
    Lussanhando: ["Lussanhando (Sede)"],
    Massengere: ["Massengere (Sede)"],
    Sanjala: ["Sanjala (Sede)"],
    Chiuaula: ["Chiuaula (Sede)"],
    Lulumile: ["Lulumile (Sede)"],
    "Malanga (Sede)": ["Malanga (Sede)", "Mecualo", "Micuinha"],
    Muaquia: ["Muaquia (Sede)", "Riate"],
    Nairobi: ["Nairobi (Sede)", "Nambilange"],
    "Mandimba (Sede)": ["Mandimba (Sede)"],
    Mitande: ["Mitande (Sede)", "Mississi"],
    Lissiete: ["Lissiete (Sede)", "Luelele", "Ntembo"],
    "Marrupa (Sede)": ["Marrupa (Sede)"],
    Nungo: ["Nungo (Sede)", "Messalo"],
    Marangira: ["Marangira (Sede)", "Massenguesse"],
    Tumpue: ["Tumpue (Sede)", "Pringilane"],
    "Maúa (Sede)": ["Maúa (Sede)", "Mugoma"],
    Maiaca: ["Maiaca (Sede)", "Muapula"],
    "Mavago (Sede)": ["N'kalapa-Mavago"],
    "M'Sawise": ["M'Sawise (Sede)"],
    Matondovela: ["Matondovela (Sede)"],
    "Mecula (Sede)": ["Mecula (Sede)", "Gomba", "Mbamba"],
    "Metarica (Sede)": ["Metarica (Sede)"],
    Mucumua: ["Mucumua"],
    Namicunde: ["Namicunde (Sede)", "Nambuara", "Mecuinica"],
    "Muembe (Sede)": ["Muembe (Sede)", "Lutuesse", "Nzizi"],
    Chiconono: ["Chiconono (Sede)", "Chiuanjota"],
    Muipite: ["Muipite-Muluco", "Cheia-cheia"],
    "Nipepe (Sede)": ["Nipepe (Sede)", "Mutomar", "Tamica"],
    "Massangulo (Sede)": ["Massangulo (Sede)", "Ngauma"],
    Itepela: ["Itepela (Sede)"],
    Lussimbesse: ["Lussimbesse (Sede)", "Cadjamba", "Luchimua"],
    "Unango (Sede)": ["Unango (Sede)"],
    Matchedje: ["Matchedje (Sede)"],
    Macaloge: ["Macaloge (Sede)", "Ndjesse"],
    Chiuta: ["Chiuta (Sede)", "Matequesso", "Carronga"],
    "Insaca (Sede)": ["Insaca (Sede)", "Iataria", "Entre-Lagos"],
  
    // Nampula
    "Angoche (Sede)": [
      "Angoche (Sede)",
      "Cerema",
      "Mutucuti",
      "Sangage",
      "Parapato",
      "Johar",
    ],
    Aube: ["Aube (Sede)", "Catamoio-Catambo"],
    Namaponda: ["Namaponda (Sede)", "Gelo", "Mepapata"],
    Boila: ["Boila (Sede)", "Naiculo", "Nabruma", "Muchepua"],
    Namapa: ["Namapa (Vila)", "Namapa (Sede)", "Odinepa"],
    Alua: ["Alua (Sede)", "Samora Machel"],
    Namiroa: ["Namiroa (Sede)", "Muanona"],
    "Ilha de Moçambique (Sede)": ["Ilha de Moçambique (Sede)"],
    Lumbo: ["Lumbo (Sede)"],
    "Lalaua (Sede)": ["Lalaua (Sede)", "Lurio"],
    Meti: ["Meti (Sede)", "Naquessa"],
    "Malema (Sede)": [
      "Malema (Vila)",
      "Malema (Sede)",
      "Muralelo",
      "Nataleia",
      "Nioce",
    ],
    Chihulo: ["Chihulo (Sede)", "Nipacue", "Nihona"],
    Mutuali: ["Mutuali (Sede)", "Nacata", "Muessi"],
    "Meconta (Sede)": ["Meconta (Vila)", "Meconta (Sede)"],
    Corrane: ["Corrane (Sede)", "Mecua 1", "Mecua 2"],
    Namialo: ["Namialo (Vila)", "Namialo (Sede)", "25 de Setembro"],
    "7 de Abril": ["7 de Abril (Sede)", "Nacoma"],
    "Mecubúri (Sede)": [
      "Mecubúri (Sede)",
      "Issipe",
      "Momane",
      "Nahipa-Marririume",
      "Natala-Popue",
    ],
    Milhana: ["Milhana (Sede)", "Malite"],
    Muite: ["Muite (Sede)", "Napai", "Ratane"],
    Namina: ["Namina (Sede)"],
    "Memba (Sede)": ["Memba (Sede)", "Tropene", "7 de Abril", "Niaca Geba"],
    Chipene: ["Chipene (Sede)"],
    "Lurio (de Memba)": ["Lurio (Sede)"],
    Mazua: ["Mazua (Sede)", "Cava", "Simuco"],
    "Namige (Sede)": ["Namige (Sede)", "Naminame"],
    Quixaxe: ["Quixaxe (Sede)", "Mepoene"],
    Nametil: ["Nametil (Vila)", "Nametil (Sede)", "Rieque", "Moquito"],
    Calipo: ["Calipo (Sede)", "Cusse", "Calipo-Tucua"],
    Iuluti: ["Iuluti (Sede)", "Mochuia", "Mputo"],
    Muatua: ["Muatua (Sede)", "Mavuruta"],
    "Nanhupo-Rio": ["Nanhupo-Rio (Sede)"],
    "Moma (Sede)": ["Moma (Sede)"],
    Macone: ["Macone (Sede)", "Mirrupi", "Naicole", "Pilivile"],
    Chalaua: ["Chalaua (Sede)", "Naicolane", "Namawi", "Piqueira"],
    "Monapo (Sede)": ["Monapo (Vila)", "Monapo (Sede)", "Canacue"],
    Itoculo: ["Itoculo (Sede)", "Murruto"],
    Netia: ["Netia (Sede)", "Muatuca", "Naculue"],
    "Mossuril (Sede)": ["Mossuril (Vila)", "Mossuril (Sede)", "Namitatari"],
    Lunga: ["Lunga (Sede)", "Vida Nova"],
    Matibane: ["Matibane (Sede)", "Nacucha"],
    "Muecate (Sede)": ["Muecate (Sede)", "Napala"],
    Imala: ["Imala (Sede)", "Gracio", "Muariua"],
    Mucoluane: ["Mocoluane (Sede)", "Kavula"],
    "Murrupula (Sede)": [
      "Murrupula (Vila)",
      "Murrupula (Sede)",
      "Kazuzu",
      "Namitotelane",
    ],
    Chinga: ["Chinga (Sede)", "Namilasse"],
    Nehessiue: ["Nehessiue (Sede)", "Mulhaniua", "Nacocolo"],
    "Mutiva (Sede)": ["Maiaia-Mutiva"],
    Muanona: ["Muanona (Sede)"],
    "Nacala-a-Velha (Sede)": ["Nacala-a-Velha (Sede)"],
    Covo: ["Covo (Sede)"],
    "Nacarôa (Sede)": ["Nacarôa (Sede)", "Mucotia", "Namirrupa"],
    Inteta: ["Nachere-Inteta", "Maheta", "Novane"],
    "Saua-Saua": ["Saua-Saua (Sede)", "Muchico", "Namila", "Teterrene"],
  
    Mutivasse: ["Mutivasse (Sede)", "Muterrua", "Nacuca"],
    Namaita: ["Namaita (Sede)", "Namiconha-Mutolo", "Nicolomua", "Poene"],
    Anchilo: ["Anchilo (Sede)", "Namachilo", "Namigonha", "Napuri", "Saua"],
    "Nampula (Cidade)": ["Nampula (Cidade)"],
    "Rapale (Sede)": ["Rapale (Sede)", "Caranja-Napome", "Tchaiane", "Nacuia"],
    "Ribáuè (Sede)": ["Ribáuè (Sede)", "Chica", "Namiconha", "Mecuasse"],
    Cunle: ["Cunle (Sedde)", "Roieque"],
    Iapala: [
      "Iapala (Vila)",
      "Iapala (Sede)",
      "Riane",
      "Noré",
      "Matharya",
      "Lupi",
    ],
  
    "Larde (Sede)": ["Larde (Sede)", "Topito"],
    Mucuali: ["Mucuali (Sede)", "Najaca"],
    "Liúpo (Sede)": ["Liúpo (Sede)"],
    Quinga: ["Quinga (Sede)", "Nacacane"],
  
    // Zambezia
    "Molócuè (Sede)": [
      "Alto Molócuè (Município)",
      "Alto Molócuè (Sede)",
      "Caiaia",
      "Chapala",
      "Ecole",
      "Nacuaca",
      "Nimala",
      "Nivava",
      "Novanana",
      "Mutala",
    ],
  
    Nauela: ["Nauela", "Muhiua", "Cololo"],
  
    "Chinde (Sede)": ["Chinde (Vila)", "Matilde", "Mucuandaia", "Pambane"],
    Micaune: ["Micaune (Sede)", "Arijuane", "Magaza", "Mitange", "Nhamatamanga"],
    "Derre (Sede)": ["Derre (Sede)"],
    Machindo: ["Machindo (Sede)"],
    Guerissa: ["Guerissa (Sede)", "Nabui"],
    "Alto Ligonha": [
      "Alto Ligonha",
      "Mirali",
      "Muiane",
      "Namireco",
      "Namihaly",
      "Namithathary",
    ],
    "Gilé (Sede)": [
      "Gilé (Sede)",
      "Khayane",
      "Mamala",
      "Nanhope",
      "Moneia",
      "Naheche",
      "Uapé",
      "Intxotcha",
      "Pury",
    ],
    "Gurué (Sede)": ["Gurué (Sede)"],
    Lioma: ["Lioma (Sede)", "Magige", "Mualijane", "Nintulo", "Tetete"],
    Mepuagiua: [
      "Mepuagiua (Sede)",
      "Incize",
      "Mugaveia",
      "Nicoropale",
      "Nipive",
      "Vehiua",
    ],
    "Ile (Sede)": [
      "Ile (Sede)",
      "Mugulama",
      "Namanda",
      "Nampevo",
      "Nipiode",
      "Phalane",
    ],
    // "Namigonha": [
    //     "Namigonha"
    // ],
    Socone: ["Mualacamue", "Coruane"],
    Gonhane: ["Gonhane"],
    Mucupia: ["Mucupia (Sede)", "Chirimane", "Ilova", "Bingagira"],
    "Luabo (Sede)": ["Luabo (Sede)", "Rovuma", "Samora Machel"],
    Chimbazo: ["25 de Setembro", "Chissamba", "Maginge", "Nzama"],
    "Lugela (Sede)": ["Mobede", "Mussengane", "Nagobo", "Puthine", "Laba"],
    Muabanama: ["Muabanama (Sede)", "Comone", "M'pemula"],
    Munhamade: ["Munhamade", "Alto Lugela", "Cuba", "Mulide", "Tenede"],
    Tucuane: ["Tucuane", "Ebide", "Mabu"],
    "Maganja da Costa": [
      "Maganja da Costa (Vila)",
      "Bala",
      "Cabuir",
      "Cariua",
      "Muzo",
    ],
    Nante: ["Nante (Sede)", "Alto Mutola", "Moneia", "Muoloa", "Nomiua"],
    "Milange (Sede)": [
      "Milange (Vila)",
      "Milange (Sede)",
      "Chitambo",
      "Vulalo",
      "Liciro",
      "Tengua",
    ],
    Majaua: ["Majauia (Sede)", "Dachudua", "Dalimba"],
    Mongue: ["Mongue (Sede)", "Dulanha", "Sabelua"],
    "Mocuba (Sede)": ["Mocuba (Cidade)", "Munhiba"],
    Mugeba: ["Mugeba (Sede)", "Muaquiua"],
    Namanjavira: ["Namanjavira (Sede)", "Alto Benfica"],
    Bajone: ["Nacuda", "Missal", "Naico"],
    "Mocubela (Sede)": ["Mocubela (Sede)", "Maneia"],
    "Molumbo (Sede)": ["Molumbo (Sede)", "Capitão Mor"],
    Corromana: ["Corromana (Sede)", "Nangoma"],
    "Mopeia (Sede)": ["Mopeia (Sede)", "N'zanza", "Rovuma", "Sambalendo"],
    Campo: ["Campo (Sede)", "Catale", "Lua Lua", "Mungane"],
    "Morrumbala (Sede)": [
      "Morrumbala (Vila)",
      "Morrumbala (Sede)",
      "Borroma",
      "Mepinha",
      "Muandiua",
      "Sabe",
    ],
    Chire: ["Chire (Sede)", "Chilomo", "Gorro"],
    Megaza: ["Megaza (Sede)", "Pinda"],
    "Mulevala (Sede)": ["Namigonha", "M'bauane", "Jajo"],
    Chiraco: ["Chiraco (Sede)", "Inturro", "Mucata"],
    "Namacurra (Sede)": [
      "Malei",
      "Namacurra (Sede)",
      "Muebele",
      "Mutange",
      "Pida",
    ],
    Macuse: ["Macuse (Sede)", "Furquia", "Mbaua", "Mexixine"],
    "Namarroi (Sede)": [
      "Namarroi (Sede)",
      "Lipali",
      "Marrea",
      "Mudine",
      "Muemue",
    ],
    Regone: ["Regone (Sede)", "Mutatala", "Nemone"],
    "Nicoadala (Sede)": ["Nicoadala (Sede)", "Munhonha", "Namacata", "Nhafuba"],
    "Pebane (Sede)": ["Quichanga", "Magiga", "Nicadine", "Ratata/Impaca"],
    Mulela: ["Mulela (Sede)", "Alto Maganha", "Malema", "Mucocoro", "Namanla"],
    Naburi: ["Naburi (Sede)", "Etaga/Mihecue", "Namahipe", "Tomeia", "Txalalane"],
    Maquival: [
      "Maquival (Sede)",
      "Longe",
      "Madal",
      "Marrongane",
      "Nangoela",
      "Zalala",
    ],
    Urbano: ["Quelimane (Cidade)"],
  };
  
  export default villages;
  